### ISSUE TITLE
Key Error: 'data' 

### ISSUE THREAD

**Issue by paulaceccon** [oh-moore/followpie#10]
Traceback (most recent call last):
File "followpie.py", line 266, in 
c,f=likeUsers(MAX_COUNT,0,tag,c,f)
File "followpie.py", line 225, in likeUsers
numResults = len(dataObj['data'])
KeyError: 'data'

ACTION = LIKE

When running the "urlFindLike":

{"meta":{"error_type":"OAuthPermissionsException","code":400,"error_message":"This request requires scope=public_content, but this access token is not authorized with this scope. The user must re-authorize your application with scope=public_content to be granted this permissions."}}

**Comment by paulaceccon** [comment]
After following this:

http://stackoverflow.com/questions/33863505/oauthpermissionsexception-instagram-api-in-sandbox

Traceback (most recent call last):
  File "followpie.py", line 267, in <module>
    c,f=likeUsers(MAX_COUNT,0,tag,c,f)
  File "followpie.py", line 231, in likeUsers
    paginationId = dataObj["pagination"]['next_max_id']
KeyError: 'next_max_id'
